language: php

php:
  - 5.6.29
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  
before_script:
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/php-coveralls --exclude-no-stmt

after_success:
  - coveralls


